name: Build AI Service

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "ai_service/**"

permissions:
  packages: write
jobs:
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u visezion --password-stdin

      - name: Build and push
        run: |
            VERSION=$(date +%Y%m%d)-${GITHUB_SHA::7}
            IMAGE=ghcr.io/visezion/hcai-ai

            docker build -t $IMAGE:latest ./ai_service
            docker tag $IMAGE:latest $IMAGE:$VERSION

            docker push $IMAGE:latest
            docker push $IMAGE:$VERSION
